
services:
  php:
    image: wodby/php:latest
    container_name: m5prog_php
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:latest
    container_name: m5prog_nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: mariadb:latest
    container_name: m5prog_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3305:3306"


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: m5prog_phpmyadmin
    environment:
     PMA_HOST: '${DB_HOST}'
     PMA_USER: '${DB_USERNAME}'
     PMA_PASSWORD: '${DB_PASSWORD}'
    depends_on:
      - db
    ports:
      - "8805:80"